# This workflow runs the addIssues script nightly

name: Nightly Project Update

# Run workflow nightly at 2am UTC
on:
  schedule:
    - cron: '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "add-issues"
  add-issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install
      
      - name: Add issues from Qiskit Terra
        env: 
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          FIELD_ID_DAYS_LAST_COMMENT_OR_REVIEW: ${{ secrets.FIELD_ID_DAYS_LAST_COMMENT_OR_REVIEW }}
          FIELD_ID_DAYS_LAST_OP_COMMIT: ${{ secrets.FIELD_ID_DAYS_LAST_OP_COMMIT }}
          REPO: qiskit/qiskit-terra
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LABELS: ["good first issue", "help wanted", "Community PR"]
          UPDATE_FIELD_BOOLS: [false, false, true]
        run: npm run add-issues
